# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapper.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmapper.proto\"2\n\x1bRequestPartitionDataRequest\x12\x13\n\x0bpartitionId\x18\x01 \x01(\t\",\n\x1cRequestPartitionDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2`\n\tMapReduce\x12S\n\x14RequestPartitionData\x12\x1c.RequestPartitionDataRequest\x1a\x1d.RequestPartitionDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTPARTITIONDATAREQUEST']._serialized_start=16
  _globals['_REQUESTPARTITIONDATAREQUEST']._serialized_end=66
  _globals['_REQUESTPARTITIONDATARESPONSE']._serialized_start=68
  _globals['_REQUESTPARTITIONDATARESPONSE']._serialized_end=112
  _globals['_MAPREDUCE']._serialized_start=114
  _globals['_MAPREDUCE']._serialized_end=210
# @@protoc_insertion_point(module_scope)
