# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x06kmeans\"+\n\rReduceRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x03(\t\"*\n\x0eReduceResponse\x12\x18\n\x10updated_centroid\x18\x01 \x01(\t2B\n\x07Reducer\x12\x37\n\x06Reduce\x12\x15.kmeans.ReduceRequest\x1a\x16.kmeans.ReduceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REDUCEREQUEST']._serialized_start=25
  _globals['_REDUCEREQUEST']._serialized_end=68
  _globals['_REDUCERESPONSE']._serialized_start=70
  _globals['_REDUCERESPONSE']._serialized_end=112
  _globals['_REDUCER']._serialized_start=114
  _globals['_REDUCER']._serialized_end=180
# @@protoc_insertion_point(module_scope)
