# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\tmapreduce\"I\n\x0bMapperInput\x12\x12\n\nstartIndex\x18\x01 \x01(\t\x12\x10\n\x08\x65ndIndex\x18\x02 \x01(\t\x12\x14\n\x0coldCentroids\x18\x03 \x01(\t\" \n\x0cMapperOutput\x12\x10\n\x08response\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPPERINPUT']._serialized_start=25
  _globals['_MAPPERINPUT']._serialized_end=98
  _globals['_MAPPEROUTPUT']._serialized_start=100
  _globals['_MAPPEROUTPUT']._serialized_end=132
# @@protoc_insertion_point(module_scope)
